

build:
	cargo build --release
	
	# rust-objcopy --binary-architecture=riscv64 --strip-all target/riscv64gc-unknown-none-elf/release/00write_a -O binary target/riscv64gc-unknown-none-elf/release/00write_a.bin

	# rust-objcopy --binary-architecture=riscv64 --strip-all target/riscv64gc-unknown-none-elf/release/01write_b -O binary target/riscv64gc-unknown-none-elf/release/01write_b.bin

	# rust-objcopy --binary-architecture=riscv64 --strip-all target/riscv64gc-unknown-none-elf/release/02write_c -O binary target/riscv64gc-unknown-none-elf/release/02write_c.bin